"""Initial migration.

Revision ID: 10cbda612772
Revises: 
Create Date: 2024-01-24 19:32:43.201081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cbda612772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id_aluno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('id_curso', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('curso',
    sa.Column('id_curso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_curso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso')
    op.drop_table('aluno')
    # ### end Alembic commands ###
