"""Initial migration

Revision ID: 338fb6de8dd6
Revises: d99312c8ccb6
Create Date: 2023-12-11 11:59:25.198376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338fb6de8dd6'
down_revision = 'd99312c8ccb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id_aluno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('profissao', sa.String(length=100), nullable=False),
    sa.Column('situacao', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.drop_table('aluno')
    # ### end Alembic commands ###
